name: auto-testing
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: sanity-check
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          pip install -r mlops/tutorial/dvc_wine/requirements.txt
          python mlops/tutorial/dvc_wine/test.py
          
          echo "## Model metrics" > report.md
          cat mlops/tutorial/dvc_wine/metrics.txt >> report.md
          
          echo "## Data viz" >> report.md
          cml-publish mlops/tutorial/dvc_wine/feature_importance.png --md >> report.md
          cml-publish mlops/tutorial/dvc_wine/residuals.png --md >> report.md
          
          cml-send-comment report.md
